default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: d5pep2oeu531l3
  host: ec2-54-243-204-221.compute-1.amazonaws.com
  port: 5432
  username: mmczqfravmnhyq
  password: pjV1BZjKKJ_UK87ehB1Gkx0rXb
  

test:
  <<: *default
  database: mtb_test

production:
  <<: *default
  database: mtb_production
  username: mtb_timinf
  password: <%= ENV['MTB_TIMING _DATABASE_PASSWORD'] %>
